// autogenerated file
export const nodes = [
  {
    "id": 0,
    "label": "neons-personal"
  },
  {
    "id": 1,
    "label": "fox-bites"
  },
  {
    "id": 2,
    "label": "ambers-mine"
  },
  {
    "id": 3,
    "label": "micahs-rabbit-hole"
  },
  {
    "id": 4,
    "label": "skyfalls-airport"
  },
  {
    "id": 5,
    "label": "tales-of-aadil"
  },
  {
    "id": 6,
    "label": "the-wild-ramblings-of-kieran"
  },
  {
    "id": 7,
    "label": "antarctica"
  },
  {
    "id": 8,
    "label": "niko-commits-vehicular-manslaughter"
  },
  {
    "id": 9,
    "label": "the-chaos-room"
  },
  {
    "id": 10,
    "label": "the-potion-pond"
  },
  {
    "id": 11,
    "label": "dinobox-den"
  },
  {
    "id": 12,
    "label": "owasis-revenge-plans"
  },
  {
    "id": 13,
    "label": "samuel-land"
  },
  {
    "id": 14,
    "label": "jeremy-rambles"
  },
  {
    "id": 15,
    "label": "adrian-goes-insane"
  },
  {
    "id": 16,
    "label": "my-personal-channel-ig"
  },
  {
    "id": 17,
    "label": "devarshs-channel"
  },
  {
    "id": 18,
    "label": "phthallocyanine"
  },
  {
    "id": 19,
    "label": "whowhatwarewhywhen"
  },
  {
    "id": 20,
    "label": "kittycats-cattery"
  },
  {
    "id": 21,
    "label": "firepup-public-chan"
  },
  {
    "id": 22,
    "label": "sarans-fuzzy-corner"
  },
  {
    "id": 23,
    "label": "noras-basement"
  },
  {
    "id": 24,
    "label": "the-hen-coop"
  },
  {
    "id": 25,
    "label": "abhay-makes-pfps"
  },
  {
    "id": 26,
    "label": "vic"
  },
  {
    "id": 27,
    "label": "enys-pirate-cove"
  },
  {
    "id": 28,
    "label": "bartosz-fans"
  },
  {
    "id": 29,
    "label": "briyansbiriyanicafe"
  },
  {
    "id": 30,
    "label": "owais-revenge-plans"
  },
  {
    "id": 31,
    "label": "the-fast-lane"
  },
  {
    "id": 32,
    "label": "zrl-land"
  },
  {
    "id": 33,
    "label": "acon-yaps"
  },
  {
    "id": 34,
    "label": "rio-updates"
  },
  {
    "id": 35,
    "label": "alex-containment-chamber"
  },
  {
    "id": 36,
    "label": "ducc-ducc-goos"
  },
  {
    "id": 37,
    "label": "pirates-port"
  },
  {
    "id": 38,
    "label": "davids-me"
  },
  {
    "id": 39,
    "label": "blahaj-land"
  },
  {
    "id": 40,
    "label": "eeriergosling"
  },
  {
    "id": 41,
    "label": "reesericdotci"
  },
  {
    "id": 42,
    "label": "alex-shark-land"
  },
  {
    "id": 43,
    "label": "zoyas-atelier"
  },
  {
    "id": 44,
    "label": "sam-is-a-horrible-procrastinator-and-cant-run-or-else-nest-will-break"
  },
  {
    "id": 45,
    "label": "msn"
  },
  {
    "id": 46,
    "label": "nimit"
  },
  {
    "id": 47,
    "label": "elijah-does-stuff"
  },
  {
    "id": 48,
    "label": "crabbys-cove"
  },
  {
    "id": 49,
    "label": "felixs-corner"
  },
  {
    "id": 50,
    "label": "the-chicken-coop"
  },
  {
    "id": 51,
    "label": "diy-tsar-bomb"
  },
  {
    "id": 52,
    "label": "lucas-cave"
  },
  {
    "id": 53,
    "label": "alex-goes-insane"
  },
  {
    "id": 54,
    "label": "tails-of-aadil"
  },
  {
    "id": 55,
    "label": "nekos-random-corner-of-the-high-school-party-she-was-invited-to-for-no-reason"
  },
  {
    "id": 56,
    "label": "aviary"
  },
  {
    "id": 57,
    "label": "3с"
  },
  {
    "id": 58,
    "label": "ajhalili2006-lair"
  }
];
export const edges = [
  {
    "from": 0,
    "to": 1
  },
  {
    "from": 0,
    "to": 2
  },
  {
    "from": 0,
    "to": 3
  },
  {
    "from": 0,
    "to": 4
  },
  {
    "from": 0,
    "to": 5
  },
  {
    "from": 0,
    "to": 6
  },
  {
    "from": 6,
    "to": 9
  },
  {
    "from": 6,
    "to": 10
  },
  {
    "from": 6,
    "to": 11
  },
  {
    "from": 6,
    "to": 12
  },
  {
    "from": 6,
    "to": 13
  },
  {
    "from": 6,
    "to": 14
  },
  {
    "from": 14,
    "to": 15
  },
  {
    "from": 14,
    "to": 16
  },
  {
    "from": 14,
    "to": 17
  },
  {
    "from": 14,
    "to": 18
  },
  {
    "from": 14,
    "to": 19
  },
  {
    "from": 14,
    "to": 20
  },
  {
    "from": 14,
    "to": 21
  },
  {
    "from": 14,
    "to": 22
  },
  {
    "from": 14,
    "to": 23
  },
  {
    "from": 14,
    "to": 24
  },
  {
    "from": 14,
    "to": 25
  },
  {
    "from": 14,
    "to": 8
  },
  {
    "from": 14,
    "to": 26
  },
  {
    "from": 3,
    "to": 4
  },
  {
    "from": 3,
    "to": 6
  },
  {
    "from": 3,
    "to": 2
  },
  {
    "from": 3,
    "to": 27
  },
  {
    "from": 3,
    "to": 10
  },
  {
    "from": 3,
    "to": 9
  },
  {
    "from": 3,
    "to": 28
  },
  {
    "from": 3,
    "to": 29
  },
  {
    "from": 3,
    "to": 30
  },
  {
    "from": 3,
    "to": 31
  },
  {
    "from": 3,
    "to": 32
  },
  {
    "from": 3,
    "to": 33
  },
  {
    "from": 3,
    "to": 34
  },
  {
    "from": 3,
    "to": 35
  },
  {
    "from": 3,
    "to": 36
  },
  {
    "from": 3,
    "to": 37
  },
  {
    "from": 38,
    "to": 39
  },
  {
    "from": 38,
    "to": 40
  },
  {
    "from": 38,
    "to": 41
  },
  {
    "from": 38,
    "to": 13
  },
  {
    "from": 38,
    "to": 42
  },
  {
    "from": 38,
    "to": 43
  },
  {
    "from": 38,
    "to": 38
  },
  {
    "from": 38,
    "to": 21
  },
  {
    "from": 38,
    "to": 44
  },
  {
    "from": 38,
    "to": 2
  },
  {
    "from": 38,
    "to": 45
  },
  {
    "from": 38,
    "to": 46
  },
  {
    "from": 50,
    "to": 13
  },
  {
    "from": 50,
    "to": 30
  },
  {
    "from": 50,
    "to": 19
  },
  {
    "from": 50,
    "to": 15
  },
  {
    "from": 50,
    "to": 39
  },
  {
    "from": 50,
    "to": 51
  },
  {
    "from": 50,
    "to": 20
  },
  {
    "from": 50,
    "to": 9
  },
  {
    "from": 50,
    "to": 25
  },
  {
    "from": 52,
    "to": 13
  },
  {
    "from": 53,
    "to": 40
  },
  {
    "from": 53,
    "to": 41
  },
  {
    "from": 53,
    "to": 13
  },
  {
    "from": 53,
    "to": 42
  },
  {
    "from": 53,
    "to": 43
  },
  {
    "from": 53,
    "to": 38
  },
  {
    "from": 55,
    "to": 56
  },
  {
    "from": 55,
    "to": 39
  },
  {
    "from": 55,
    "to": 2
  },
  {
    "from": 55,
    "to": 19
  },
  {
    "from": 55,
    "to": 57
  },
  {
    "from": 55,
    "to": 9
  }
];